// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(PoofDbContext))]
    partial class PoofDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Suite")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = "1e5ec8e7-c1d7-4deb-b4f5-31e4fd717a70",
                            Description = "The Barrel allows you to “draw!” when you are the target of a BANG! if you draw a Heart card, you are Missed! (just like if you played a Missed! card)-otherwise nothing happens.",
                            Name = "Barrel",
                            Suite = 0,
                            Type = 0,
                            Value = 10
                        },
                        new
                        {
                            Id = "4b36687f-9739-4d15-b812-6e30f5494ac7",
                            Description = "The Barrel allows you to “draw!” when you are the target of a BANG! if you draw a Heart card, you are Missed! (just like if you played a Missed! card)-otherwise nothing happens.",
                            Name = "Barrel",
                            Suite = 0,
                            Type = 0,
                            Value = 11
                        },
                        new
                        {
                            Id = "617bdd17-e535-4551-9890-f33bff71bf39",
                            Description = "Play this card in front of you: the Dynamite will stay there for a whole turn. When you start your next turn(you have the Dynamite already in play), before the first phase you must draw! if you draw a card showing Spades and a number between 2 and 9, the Dynamite explodes! Discard it and lose 3 life points; otherwise, pass the Dynamite to the player on your left(who will draw! on his turn, etc)..Players keep passing the Dynamite around until it explodes, with the effect explained above, or it is drawn or discarded by a Panic!or a Cat Balou.If you have both the Dynamite and a Jail in play, check the Dynamite first. If you are damaged(or even eliminated!) by a Dynamite, this damage is not considered to be caused by any player.",
                            Name = "Dynamite",
                            Suite = 1,
                            Type = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = "799a20d7-a7e4-4aa8-a4c7-4df975fe1bc3",
                            Description = "Play this card in front of you: the Dynamite will stay there for a whole turn. When you start your next turn(you have the Dynamite already in play), before the first phase you must draw! if you draw a card showing Spades and a number between 2 and 9, the Dynamite explodes! Discard it and lose 3 life points; otherwise, pass the Dynamite to the player on your left(who will draw! on his turn, etc)..Players keep passing the Dynamite around until it explodes, with the effect explained above, or it is drawn or discarded by a Panic!or a Cat Balou.If you have both the Dynamite and a Jail in play, check the Dynamite first. If you are damaged(or even eliminated!) by a Dynamite, this damage is not considered to be caused by any player.",
                            Name = "Dynamite",
                            Suite = 1,
                            Type = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = "ef8df827-0adc-4f71-a328-2cb7a3af7a83",
                            Description = "Play this card in front of any player regardless of the distance: you put him in jail! If you are in jail, you must draw! before the beginning of your turn: if you draw a Heart card, you escape from jail: discard the Jail, and continue your turn as normal otherwise discard the Jail and skip your turn. If you are in Jail you remain a possible target for BANG! cards and can still play response cards (e.g. Missed! and Beer) out of your turn, if necessary. Jail cannot be played on the Sheriff.",
                            Name = "Jail",
                            Suite = 0,
                            Type = 0,
                            Value = 9
                        },
                        new
                        {
                            Id = "92976b77-5341-4c76-9c00-b76b6d12b4eb",
                            Description = "Play this card in front of any player regardless of the distance: you put him in jail! If you are in jail, you must draw! before the beginning of your turn: if you draw a Heart card, you escape from jail: discard the Jail, and continue your turn as normal otherwise discard the Jail and skip your turn. If you are in Jail you remain a possible target for BANG! cards and can still play response cards (e.g. Missed! and Beer) out of your turn, if necessary. Jail cannot be played on the Sheriff.",
                            Name = "Jail",
                            Suite = 1,
                            Type = 0,
                            Value = 2
                        },
                        new
                        {
                            Id = "73625043-67da-4f6e-9b64-99e947e326a0",
                            Description = "Play this card in front of any player regardless of the distance: you put him in jail! If you are in jail, you must draw! before the beginning of your turn: if you draw a Heart card, you escape from jail: discard the Jail, and continue your turn as normal otherwise discard the Jail and skip your turn. If you are in Jail you remain a possible target for BANG! cards and can still play response cards (e.g. Missed! and Beer) out of your turn, if necessary. Jail cannot be played on the Sheriff.",
                            Name = "Jail",
                            Suite = 0,
                            Type = 0,
                            Value = 8
                        },
                        new
                        {
                            Id = "8c4ff17e-5b44-42bc-90a1-150d5c484ed8",
                            Description = "When you have a Mustang horse in play the distance between other players and you is increased by 1. However, you still see the other players at the normal distance.",
                            Name = "Mustang",
                            Suite = 1,
                            Type = 0,
                            Value = 6
                        },
                        new
                        {
                            Id = "28f69fee-54aa-48cc-bee9-adcae4ec622f",
                            Description = "When you have a Mustang horse in play the distance between other players and you is increased by 1. However, you still see the other players at the normal distance.",
                            Name = "Mustang",
                            Suite = 1,
                            Type = 0,
                            Value = 6
                        },
                        new
                        {
                            Id = "a73eff5b-7e01-46c9-b48f-325af62cfb00",
                            Description = "",
                            Name = "Remington",
                            Suite = 2,
                            Type = 1,
                            Value = 11
                        },
                        new
                        {
                            Id = "f33fc607-5027-4fe7-a8b9-01b6bb28d40c",
                            Description = "",
                            Name = "Carabine",
                            Suite = 2,
                            Type = 1,
                            Value = 12
                        },
                        new
                        {
                            Id = "41e3816f-2534-4c6e-9df6-0323af5b00c9",
                            Description = "",
                            Name = "Schofield",
                            Suite = 2,
                            Type = 1,
                            Value = 9
                        },
                        new
                        {
                            Id = "9ce4fcc7-9102-45e3-b38a-904af7e0d398",
                            Description = "",
                            Name = "Schofield",
                            Suite = 2,
                            Type = 1,
                            Value = 10
                        },
                        new
                        {
                            Id = "579a1b80-4efe-4944-89e4-7c1487ee5415",
                            Description = "",
                            Name = "Schofield",
                            Suite = 2,
                            Type = 1,
                            Value = 11
                        },
                        new
                        {
                            Id = "55fca9d2-1bd4-4d54-a053-2f8bb0fd5dc0",
                            Description = "",
                            Name = "Volcanic",
                            Suite = 2,
                            Type = 1,
                            Value = 8
                        },
                        new
                        {
                            Id = "91249d15-8ecf-4637-b235-9bdbcfd5268f",
                            Description = "",
                            Name = "Volcanic",
                            Suite = 0,
                            Type = 1,
                            Value = 8
                        },
                        new
                        {
                            Id = "74bcee38-37e2-4a77-81c8-d402dbefbfa3",
                            Description = "",
                            Name = "Winchester",
                            Suite = 2,
                            Type = 1,
                            Value = 8
                        },
                        new
                        {
                            Id = "0f084b5c-bb57-41d9-81cb-b4e0b2abf894",
                            Description = "When you have a Scope in play, you see all the other players at a distance decreased by 1.",
                            Name = "Scope",
                            Suite = 0,
                            Type = 0,
                            Value = 12
                        },
                        new
                        {
                            Id = "995209c0-c237-49b1-99e8-dd57439da22a",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 0,
                            Type = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = "b9a3429a-7506-4b82-81ac-07fb8554b91a",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = "147d0858-6e91-4041-8ff3-d1d3e6fe29c1",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = "4f8d0a17-b9b6-44f4-9e82-edc3316b0dd8",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = "6b7aed1b-89dd-4369-914d-c31185c11fd3",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = "e68b70f7-a614-40c1-ab31-60a60835dda6",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = "9276d633-8e68-4c1f-9fc5-e8fd18280d6c",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = "8a4848c6-3e4e-4321-b5c8-f389db3ff43d",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 6
                        },
                        new
                        {
                            Id = "38f2c70b-13d7-4d24-9586-bc19c76671ad",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 7
                        },
                        new
                        {
                            Id = "923d42a0-e35a-42a8-bc83-c00095877fe2",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 8
                        },
                        new
                        {
                            Id = "1c933d6e-7550-4e4d-b45a-913d004c9943",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 9
                        },
                        new
                        {
                            Id = "d7294a34-37d8-4224-b88c-afe86d4d68df",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 10
                        },
                        new
                        {
                            Id = "a3e9c7ad-fd04-4453-9bc1-ad5f4d7a9db5",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 11
                        },
                        new
                        {
                            Id = "7dd2e4be-60ef-4d56-809d-3a0b11e74191",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 3,
                            Type = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = "8868979c-dec9-43d8-a6dc-82f0f500ad20",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 2,
                            Type = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = "d5c96a10-870d-45ee-b7c5-0a0ce8753186",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 2,
                            Type = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = "dbf53655-deeb-400e-9133-7040b82b3e6e",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 2,
                            Type = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = "f768f0b2-ab65-437d-8507-61d27b6fe71b",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 2,
                            Type = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = "6c19481f-01ec-48fa-a915-c52bd0dca7a8",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 2,
                            Type = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = "b0bb15f8-1ae2-4bb5-a124-9e08ff0103a1",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 2,
                            Type = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = "984716df-c19a-4a2e-9e26-bbe5ab2760f9",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 2,
                            Type = 2,
                            Value = 6
                        },
                        new
                        {
                            Id = "4fb4bf76-fd2f-45c1-9ef9-e0cc747a8cdf",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 2,
                            Type = 2,
                            Value = 7
                        },
                        new
                        {
                            Id = "86d6c584-adb8-4614-a9ba-d04ff79ef2ff",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 1,
                            Type = 2,
                            Value = 10
                        },
                        new
                        {
                            Id = "fa21eebb-a585-4a7b-bee1-9679f56d1d29",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 1,
                            Type = 2,
                            Value = 11
                        },
                        new
                        {
                            Id = "cf8f49d6-013b-4341-a04d-2552fe153286",
                            Description = "BANG! cards are the main method to reduce other players' ife points. If you want to play a BANG! card to hit one of the players, determine: what the distance to that player is; and if your weapon is capable of reaching that distance.",
                            Name = "Bang",
                            Suite = 1,
                            Type = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = "9e1ffb10-40c1-4acb-9dc0-341b5d444a49",
                            Description = "This card lets you regain one life point - take a bullet from the pile. You cannot gain more life points than your starting amount! The Beer cannot be used to help other players. The Beer can be played in two ways: as usual, during your turn and out of turn, but only if you have just received a hit that is lethal (i.e. a hit that takes away your last life point), and not if you are simply hit. Beer has no effect if there are only 2 players left in the game; in other words, if you play a Beer you do not gain any life point.",
                            Name = "Beer",
                            Suite = 1,
                            Type = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = "d24fbcea-cdb5-448a-88db-6a40a87e5bb5",
                            Description = "This card lets you regain one life point - take a bullet from the pile. You cannot gain more life points than your starting amount! The Beer cannot be used to help other players. The Beer can be played in two ways: as usual, during your turn and out of turn, but only if you have just received a hit that is lethal (i.e. a hit that takes away your last life point), and not if you are simply hit. Beer has no effect if there are only 2 players left in the game; in other words, if you play a Beer you do not gain any life point.",
                            Name = "Beer",
                            Suite = 1,
                            Type = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = "50e71c77-4bd0-41eb-b85f-2b7fcadc2350",
                            Description = "This card lets you regain one life point - take a bullet from the pile. You cannot gain more life points than your starting amount! The Beer cannot be used to help other players. The Beer can be played in two ways: as usual, during your turn and out of turn, but only if you have just received a hit that is lethal (i.e. a hit that takes away your last life point), and not if you are simply hit. Beer has no effect if there are only 2 players left in the game; in other words, if you play a Beer you do not gain any life point.",
                            Name = "Beer",
                            Suite = 1,
                            Type = 2,
                            Value = 6
                        },
                        new
                        {
                            Id = "e756be70-bdf1-428a-96f9-19d93c420c85",
                            Description = "This card lets you regain one life point - take a bullet from the pile. You cannot gain more life points than your starting amount! The Beer cannot be used to help other players. The Beer can be played in two ways: as usual, during your turn and out of turn, but only if you have just received a hit that is lethal (i.e. a hit that takes away your last life point), and not if you are simply hit. Beer has no effect if there are only 2 players left in the game; in other words, if you play a Beer you do not gain any life point.",
                            Name = "Beer",
                            Suite = 1,
                            Type = 2,
                            Value = 7
                        },
                        new
                        {
                            Id = "bff2c1d5-f636-4a69-bebf-d9929bbe9ba8",
                            Description = "This card lets you regain one life point - take a bullet from the pile. You cannot gain more life points than your starting amount! The Beer cannot be used to help other players. The Beer can be played in two ways: as usual, during your turn and out of turn, but only if you have just received a hit that is lethal (i.e. a hit that takes away your last life point), and not if you are simply hit. Beer has no effect if there are only 2 players left in the game; in other words, if you play a Beer you do not gain any life point.",
                            Name = "Beer",
                            Suite = 1,
                            Type = 2,
                            Value = 8
                        },
                        new
                        {
                            Id = "c7ffb34d-e459-4a7d-bcd1-891fd2f6bc00",
                            Description = "This card lets you regain one life point - take a bullet from the pile. You cannot gain more life points than your starting amount! The Beer cannot be used to help other players. The Beer can be played in two ways: as usual, during your turn and out of turn, but only if you have just received a hit that is lethal (i.e. a hit that takes away your last life point), and not if you are simply hit. Beer has no effect if there are only 2 players left in the game; in other words, if you play a Beer you do not gain any life point.",
                            Name = "Beer",
                            Suite = 1,
                            Type = 2,
                            Value = 9
                        },
                        new
                        {
                            Id = "58847b2a-eaef-4dac-8012-4816fbe8ba07",
                            Description = "Force any one player to discard a card, regardless of the distance.",
                            Name = "Cat Balou",
                            Suite = 1,
                            Type = 2,
                            Value = 11
                        },
                        new
                        {
                            Id = "6e6d14e6-e3b9-4d8d-8c73-890e8610532b",
                            Description = "Force any one player to discard a card, regardless of the distance.",
                            Name = "Cat Balou",
                            Suite = 3,
                            Type = 2,
                            Value = 7
                        },
                        new
                        {
                            Id = "992ba3ca-effb-44df-8ab5-dfed468a4287",
                            Description = "Force any one player to discard a card, regardless of the distance.",
                            Name = "Cat Balou",
                            Suite = 3,
                            Type = 2,
                            Value = 8
                        },
                        new
                        {
                            Id = "bab84577-cb53-41cb-a06d-fffadd4e1072",
                            Description = "Force any one player to discard a card, regardless of the distance.",
                            Name = "Cat Balou",
                            Suite = 3,
                            Type = 2,
                            Value = 9
                        },
                        new
                        {
                            Id = "026e75ad-fd88-49a9-b88a-09f8e8908ade",
                            Description = "Draw two cards from the top of the deck",
                            Name = "Stagecoach",
                            Suite = 0,
                            Type = 2,
                            Value = 7
                        },
                        new
                        {
                            Id = "5e327fb8-aa07-4be9-8633-850bbeadc30f",
                            Description = "Draw two cards from the top of the deck",
                            Name = "Stagecoach",
                            Suite = 0,
                            Type = 2,
                            Value = 7
                        },
                        new
                        {
                            Id = "8d16c01d-2b55-4499-abb6-bd9c2c3e3502",
                            Description = "With this card you can challenge any other player (staring him in the eyes!), regardless of the distance. The challenged player may discard a BANG! card (even though it is not his turn!). If he does, you may discard a BANG! card, and so on: the first player failing to discard a BANG! card loses one life point, and the duel is I over. You cannot play Missed! or use the Barrel during a duel. The Duel is not a BANG! card. BANG! cards discarded during a Duel are not accounted towards the one BANG! card limitation.",
                            Name = "Duel",
                            Suite = 3,
                            Type = 2,
                            Value = 10
                        },
                        new
                        {
                            Id = "7a51deef-4682-4d06-98bb-dc514811bf52",
                            Description = "With this card you can challenge any other player (staring him in the eyes!), regardless of the distance. The challenged player may discard a BANG! card (even though it is not his turn!). If he does, you may discard a BANG! card, and so on: the first player failing to discard a BANG! card loses one life point, and the duel is I over. You cannot play Missed! or use the Barrel during a duel. The Duel is not a BANG! card. BANG! cards discarded during a Duel are not accounted towards the one BANG! card limitation.",
                            Name = "Duel",
                            Suite = 0,
                            Type = 2,
                            Value = 9
                        },
                        new
                        {
                            Id = "b6c8cf93-f0a3-4894-9716-37dd5de16d38",
                            Description = "With this card you can challenge any other player (staring him in the eyes!), regardless of the distance. The challenged player may discard a BANG! card (even though it is not his turn!). If he does, you may discard a BANG! card, and so on: the first player failing to discard a BANG! card loses one life point, and the duel is I over. You cannot play Missed! or use the Barrel during a duel. The Duel is not a BANG! card. BANG! cards discarded during a Duel are not accounted towards the one BANG! card limitation.",
                            Name = "Duel",
                            Suite = 2,
                            Type = 2,
                            Value = 6
                        },
                        new
                        {
                            Id = "985e1e59-b3f9-4164-b100-ca8012686995",
                            Description = "The Gatling shoots a BANG! to all the other players, regardless of the distance. Even though the Gatling shoots a BANG! to all the other players, it is not considered a BANG! card. During your turn you can play any number of Gatling, but only one BANG! card.",
                            Name = "Gatling",
                            Suite = 1,
                            Type = 2,
                            Value = 8
                        },
                        new
                        {
                            Id = "6b8e207a-dd84-41c4-a940-66efb46e0d5e",
                            Description = "When you play this card, turn as many cards from the deck face up as the players still playing. Starting with you and proceeding clockwise, each player chooses one of those cards and puts it in his hands.",
                            Name = "General Store",
                            Suite = 2,
                            Type = 2,
                            Value = 7
                        },
                        new
                        {
                            Id = "a3ba93be-56b7-4038-8316-0e7bbf6e0bcd",
                            Description = "When you play this card, turn as many cards from the deck face up as the players still playing. Starting with you and proceeding clockwise, each player chooses one of those cards and puts it in his hands.",
                            Name = "General Store",
                            Suite = 0,
                            Type = 2,
                            Value = 10
                        },
                        new
                        {
                            Id = "f827c908-fa5f-4600-b5cb-d1706b401531",
                            Description = "Each player, excluding the one who played this card, may discard a BANG! card, or lose one life point. Neither Missed! nor Barrel have effect in this case.",
                            Name = "Indians!",
                            Suite = 3,
                            Type = 2,
                            Value = 11
                        },
                        new
                        {
                            Id = "dff12a31-ed7f-4676-9e59-68e261914c4b",
                            Description = "Each player, excluding the one who played this card, may discard a BANG! card, or lose one life point. Neither Missed! nor Barrel have effect in this case.",
                            Name = "Indians!",
                            Suite = 3,
                            Type = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = "0ec5f375-5ca6-438f-bf98-c9cbec5c34d8",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 2,
                            Type = 2,
                            Value = 8
                        },
                        new
                        {
                            Id = "a14a1011-a4bf-44db-a355-cb909dbe8d3b",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 2,
                            Type = 2,
                            Value = 9
                        },
                        new
                        {
                            Id = "1847e015-bb3f-4487-9ed8-ffd60a4febb3",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 2,
                            Type = 2,
                            Value = 10
                        },
                        new
                        {
                            Id = "9cfd78f4-c64d-4938-9c1f-9fc3814e85cc",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 2,
                            Type = 2,
                            Value = 11
                        },
                        new
                        {
                            Id = "1dd17c8a-e4a6-410b-a66b-16304b03aa70",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 2,
                            Type = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = "65ff1ce7-b605-473d-8984-5ef3535bd268",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 0,
                            Type = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = "197776eb-869c-4e94-940c-55b2f3310622",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 0,
                            Type = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = "c9526278-2600-4dfb-9e67-92b45aa64f0c",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 0,
                            Type = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = "d4a7a104-c9af-4684-8f45-485ccf99c295",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 0,
                            Type = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = "011d9800-8195-423c-aa3a-527f3a9e52bd",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 0,
                            Type = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = "e0170649-a7ed-4af2-9319-ea67656dab80",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 0,
                            Type = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = "1eae789f-c025-439a-aa87-822fbf46d76e",
                            Description = "If you are hit by a BANG! you may immediately play a Missed! - even though it is not your turn! - to cancel the shot. If you do not, you lose one life point (discard a bullet). Discarded bullet go into a pile in the middle of the table.",
                            Name = "Missed!",
                            Suite = 0,
                            Type = 2,
                            Value = 6
                        },
                        new
                        {
                            Id = "3da946f5-86b6-44c5-ba5f-c6e39dc55398",
                            Description = "The symbols state: Draw a card from a player at distance 1. Remember that this distance is not modified by weapons, but only by cards such as Mustang and/or Scope.",
                            Name = "Panic!",
                            Suite = 1,
                            Type = 2,
                            Value = 9
                        },
                        new
                        {
                            Id = "cddd8dcd-3db8-4e4a-85d1-ea58f994f319",
                            Description = "The symbols state: Draw a card from a player at distance 1. Remember that this distance is not modified by weapons, but only by cards such as Mustang and/or Scope.",
                            Name = "Panic!",
                            Suite = 1,
                            Type = 2,
                            Value = 10
                        },
                        new
                        {
                            Id = "1af00051-77d6-4da2-ac63-9866db8ebb58",
                            Description = "The symbols state: Draw a card from a player at distance 1. Remember that this distance is not modified by weapons, but only by cards such as Mustang and/or Scope.",
                            Name = "Panic!",
                            Suite = 1,
                            Type = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = "bf073e80-6d78-4f60-b823-1048614aac0e",
                            Description = "The symbols state: Draw a card from a player at distance 1. Remember that this distance is not modified by weapons, but only by cards such as Mustang and/or Scope.",
                            Name = "Panic!",
                            Suite = 3,
                            Type = 2,
                            Value = 6
                        },
                        new
                        {
                            Id = "05e1b8d4-693e-4554-a49d-c1c78c2f7a78",
                            Description = "Cards with symbols on two lines have two simultaneous effects, one for each line. Here symbols say: Regain one life point, and this applies to All the other players, and on the next line: [You] regain one life point. The overall effect is that all players in play regain one life point. You cannot play a Saloon out of turn when you are losing your last life point: the Saloon is not a Beer!",
                            Name = "Saloon",
                            Suite = 1,
                            Type = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = "d7a1f350-1c85-4c32-9e67-f41f102a95d1",
                            Description = "Draw three cards from the top of the deck",
                            Name = "Wells Fargo",
                            Suite = 1,
                            Type = 2,
                            Value = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AimDistance")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LifePoint")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBangs")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeaponId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Domain.Entities.Connection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LobbyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConnectionId");

                    b.HasIndex("LobbyName");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Domain.Entities.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Domain.Entities.GameCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GameId");

                    b.ToTable("GameCards");
                });

            modelBuilder.Entity("Domain.Entities.Lobby", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Vezeto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Kuldo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LobbyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tartalom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LobbyName");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("GameId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GameId1");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Domain.Entities.RoleCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LifePoint")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleCards");

                    b.HasData(
                        new
                        {
                            Id = "8c52aa39-7ee4-4b1a-b63c-dcb561198ecf",
                            Description = "Each time he is hit, he draws a card",
                            LifePoint = 4,
                            Name = "Bart Cassidy"
                        },
                        new
                        {
                            Id = "86536e3f-4b15-4a6e-8a02-2727484b9990",
                            Description = "He shows the second card he draw. On Heart or Diamonds, he draws one more card",
                            LifePoint = 4,
                            Name = "Black Jack"
                        },
                        new
                        {
                            Id = "9cb1846b-1499-4d64-8bc5-2e0eb857400f",
                            Description = "She can use BANG! cards as Missed! cards and vice versa. If she plays a Missed! as a BANG!, she cannot play another BANG! card that turn (unless she has a Volcanic in play).",
                            LifePoint = 4,
                            Name = "Calamity Janet"
                        },
                        new
                        {
                            Id = "8e917c46-5920-4208-ac32-5f2b8e23441a",
                            Description = "Each time he loses a life point due to a card played by another player, he draws a random card from the hands of that player (one card for each life point). If that player has no more cards, too bad!, he does not draw. Note that Dynamite damages are not caused by any player.",
                            LifePoint = 3,
                            Name = "El Gringo"
                        },
                        new
                        {
                            Id = "6d4b3bc9-0689-41d8-b9ae-ad3c0bda0a8c",
                            Description = "During phase 1 of his turn, he may choose to draw the first card from the deck, or randomly from the hand of any other player. Then he draws the second card from the deck.",
                            LifePoint = 4,
                            Name = "Jesse Jones"
                        },
                        new
                        {
                            Id = "ace22034-0064-454b-a7da-01c3f21c9714",
                            Description = "He is considered to have a Barrel in play at all times; he can draw! when he is the target of a BANG!, and on a Heart he is missed. If he has another real Barrel card in play, he can count both of them, giving him two chances to cancel the BANG! before playing a Missed!.",
                            LifePoint = 4,
                            Name = "Jourdonnais"
                        },
                        new
                        {
                            Id = "2439e6b3-9254-45fd-ac05-f303ec90a5b4",
                            Description = "During phase 1 of his turn, he looks at the top three cards of the deck: he chooses 2 to draw, and puts the other one back on the top of the deck, face down.",
                            LifePoint = 4,
                            Name = "Kit Carlson"
                        },
                        new
                        {
                            Id = "1af0014f-aa21-406d-a00f-9a51bb13356f",
                            Description = "Each time he is required to draw!, he flips the top two cards from the deck and chooses the result he prefers. Discard both cards afterward.",
                            LifePoint = 4,
                            Name = "Lucky Duke"
                        },
                        new
                        {
                            Id = "6d5a30a4-ddb8-48eb-b7ff-d93f9c3b8e08",
                            Description = "he is considered to have a Mustang in play at all times; all other players must add 1 to the distance to him. If he has another real Mustang in play, he can count both of them, increasing all distances to him by a total of 2.",
                            LifePoint = 3,
                            Name = "Paul Regret"
                        },
                        new
                        {
                            Id = "7deed5cd-8bde-4d79-a5d1-678d79984728",
                            Description = "During phase 1 of his turn, he may choose to draw the first card from the top of the discard pile or from the deck. Then, he draws the second card from the deck.",
                            LifePoint = 4,
                            Name = "Pedro Ramirez"
                        },
                        new
                        {
                            Id = "377e6d31-a5d5-4d80-85e1-4b6926c84d29",
                            Description = "She is considered to have a Scope in play at all times; she sees the other players at a distance decreased by 1. If she has another real Scope in play, she can count both of them, reducing her distance to all other players by a total of 2.",
                            LifePoint = 4,
                            Name = "Rose Doolan"
                        },
                        new
                        {
                            Id = "83d60c82-770d-4f9c-82d1-079649799b7f",
                            Description = "At any time, he may discard 2 cards from his hand to regain one life point. If he is willing and able, he can use this ability more than once at a time. But remember: you cannot have more life points than your starting amount!",
                            LifePoint = 4,
                            Name = "Sid Ketchum"
                        },
                        new
                        {
                            Id = "6b37a20b-b5d2-42d0-9cd2-ac924e6a658e",
                            Description = "Players trying to cancel his BANG! cards need to play 2 Missed!. The Barrel effect, if successfully used, only counts as one Missed!.",
                            LifePoint = 4,
                            Name = "Slab the Killer"
                        },
                        new
                        {
                            Id = "2602ae98-3eb2-43bb-9cec-fe9ac0b341c6",
                            Description = "As soon as she has no cards in her hand, she draws a card from the draw pile.",
                            LifePoint = 4,
                            Name = "Suzy Lafayette"
                        },
                        new
                        {
                            Id = "e8999773-6289-44fb-b00f-4d8162eada6d",
                            Description = "Whenever a character is eliminated from the game, Sam takes all the cards that player had in his hand and in play, and adds them to his hand.",
                            LifePoint = 4,
                            Name = "Vulture Sam"
                        },
                        new
                        {
                            Id = "33e32467-694c-4b2e-af75-0f36ad9ae2c8",
                            Description = "He can play any number of BANG! cards during his turn.",
                            LifePoint = 4,
                            Name = "Willy the Kid"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("Characters")
                        .HasForeignKey("GameId");

                    b.HasOne("Domain.Entities.RoleCard", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("Domain.Entities.Card", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId");

                    b.Navigation("Game");

                    b.Navigation("Role");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Domain.Entities.Connection", b =>
                {
                    b.HasOne("Domain.Entities.Lobby", null)
                        .WithMany("Connections")
                        .HasForeignKey("LobbyName");
                });

            modelBuilder.Entity("Domain.Entities.GameCard", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("Domain.Entities.Game", null)
                        .WithMany("Deck")
                        .HasForeignKey("GameId");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.HasOne("Domain.Entities.Game", null)
                        .WithMany("Messages")
                        .HasForeignKey("GameId");

                    b.HasOne("Domain.Entities.Lobby", null)
                        .WithMany("Messages")
                        .HasForeignKey("LobbyName");
                });

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId1");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Game", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Deck");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Lobby", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
