name: bang
description: Bang! ripoff
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_crashlytics: ^2.2.1
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_performance: ^0.7.1
  get_storage: ^2.0.3
  get: ^4.3.8
  lottie: ^1.2.0
  google_fonts: ^2.1.0
  connectivity_plus: ^1.1.0
  just_audio: ^0.9.11
  wakelock: ^0.5.6
  shared_preferences: ^2.0.8
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2
  fluttertoast: ^8.0.8
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  font_awesome_flutter: ^9.1.0
  animated_icon_button: ^1.0.2
  cupertino_icons: ^1.0.2
  signalr_core: ^1.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.1.5
  flutter_native_splash: ^1.2.3
 

flutter_native_splash: 
  image: "assets/icons/splash.png"
  background_image: "assets/background/bg2.png"
  fullscreen: true
  android_gravity: center

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher.png"
  adaptive_icon_background: "assets/background/bg2.png"
  adaptive_icon_foreground: "assets/icons/launcher.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/animations/boom_.json
    - assets/animations/no_internet.json
    - assets/sfx/dynamite.mp3
    - assets/cards/character/
    - assets/cards/role/
    - assets/cards/playable/
    - assets/music/
    - assets/icons/
    - assets/background/


